dbt_project:
 outputs:
   dev:
     type: postgres
     threads: 1
     host: localhost
     port: 5432
     user: myusername
     pass: mypassword
     dbname: postgres
     schema: public
 target: dev


 #docker run --name postgres -e POSTGRES_USER=myusername -e POSTGRES_PASSWORD=mypassword -p 5432:5432 -v ____/revv_project  -d postgres