version: 2

models:
  - name: dim_customer
    description: "customers dimension table"
    columns:
      - name: customer_id
        description: "The primary key for this table"

# models:
#   - name: fct_payment
#     config:
#       contract:
#         enforced: true
#     columns:
#       - name: payment_id
#         data_type: int
#         constraints:
#           - type: not_null
#           - type: primary_key
#       - name: subscription_id
#         data_type: int
#         constraints:
#           - type: not_null
#           - type: foreign_key
#       - name: customer_id
#         data_type: int
#         constraints:
#           - type: not_null
#           - type: foreign_key
#       - name: amount
#         data_type: int
#       - name: date
#         data_type: date